# Generated by Django 3.2.25 on 2024-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('name',), name='language_name_case_insensitive_unique'),
        ),
    ]
