name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t django-app .

      # Run the container to ensure it stays up
      - name: Run container
        run: |
          docker run -d -p 8000:8000 django-app

      # Check if the container is running
      - name: Verify container is running
        run: |
          docker ps
