name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 檢查代碼出儲存庫
      - name: Checkout code
        uses: actions/checkout@v3

      # 設置 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 安裝依賴
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r django-requirements.txt

      # 安裝 Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # 構建 Docker 映像並啟動服務
      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d

      # 檢查容器是否在運行 (可選步驟)
      - name: Verify that Docker containers are running
        run: |
          docker ps

      # 等待容器中的 Django 應用啟動（添加延遲）
      - name: Wait for Django server to be ready
        run: |
          sleep 10  # 等待 10 秒，確保伺服器啟動

      # 測試應用是否可以正常訪問 (可選步驟)
      - name: Test the Django server
        run: |
          curl http://localhost:8000

      # 登錄到 Azure
      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 部署到 Azure Web App
      - name: 'Deploy to Azure Web Ap'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<djangotest>'  # 替換為你的 Azure Web App 名稱
          images: 'cao0085/django-app:latest'   # 替換為你在 Docker 中構建的映像名稱
