name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r django-requirements.txt

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 5  # 等待幾秒鐘以確保容器已啟動

      - name: Check if Django is running
        run: |
          curl -v http://localhost:8000 || echo "Django is not running"

      - name: List Docker images
        run: docker images  # 確認映像是否已構建
      
      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy entire repository to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'djangotest'
          package: '.'  # 指定上傳整個儲存庫
